### ISSUE TITLE
Remove legacy setup.py

### ISSUE THREAD

**Issue by andrewphilipsmith** [Living-with-machines/alto2txt#44]
Currently, the python package is managed using poetry.

However, it calls the legacy `setup.py` setuptools process. 

It would be cleaner to remove this legacy component and use poetry natively

**Comment by griff-rees** [comment]
Hey @andrewphilipsmith thanks for the issue. A local build with `poetry` doesn't seem to make use of `setup.py` (as of d71cfc8). Is it more an issue of how it's deployed on `TestPyPI`?

**Comment by griff-rees** [comment]
I think this is addressed with #51 but worth making sure a subsequent release on `PyPI` is ok.

**Comment by griff-rees** [comment]
I think this is addressed with #51 and remaining deploy issues are covered in ticket #53
