### ISSUE TITLE
Switch PyPI deployment to a generic LwM account

### ISSUE THREAD

**Issue by andrewphilipsmith** [Living-with-machines/alto2txt#48]

**Comment by davanstrien** [comment]
> I haven't found an example account for this yet. [DeezyMatch](https://pypi.org/project/DeezyMatch/) lists LwM but it's deployed under @kasra-hosseini's account: [pypi.org/user/khosseinizad](https://pypi.org/user/khosseinizad/)

AFAIK no such account exists. I think we should discuss as a team if that makes sense or not. This is probably part of a broader discussion about if/how code projects are maintained beyond the lifetime of LwM.

**Comment by griff-rees** [comment]
@davanstrien guessing this should got to a different milestone then? @andrewphilipsmith am I right thinking you've got this to test deploy via your `PyPI` account at the moment?

**Comment by davanstrien** [comment]
> @davanstrien guessing this should got to a different milestone then? @andrewphilipsmith am I right thinking you've got this to test deploy via your `PyPI` account at the moment?

My preference would be to wait with that until it's been established that this is the approach we want to take (and have decided how this will be managed at the end of the project). A compromise might be to make multiple people maintainers so we reduce the bus factor slightly. 

In general, with this particular case, I would probably prefer to hold off making it available via PyPI until we've fixed some of the remaining bugs/rough edges and encourage people who want to use the software in its current form to do a git install i.e. `python -m pip install git+https://github.com/Living-with-machines/alto2txt.git` but others might be keen to push ahead with the PyPI install already.

**Comment by griff-rees** [comment]
Sorry for my slow reply: it is already up on `PyPI` as 1 July on https://pypi.org/project/alto2txt/ and maintained by @andrewphilipsmith through his account: https://pypi.org/user/andysmith/.

@davanstrien or others (@DavidBeavan perhaps?) if you would like this taken down we can try to sort (apologies in advance if so to @andrewphilipsmith). Also: is there a general ticket for `Living-with-Machines` regarding managing libraries generally?

**Comment by davanstrien** [comment]
> Sorry for my slow reply: it is already up on `PyPI` as 1 July on [pypi.org/project/alto2txt](https://pypi.org/project/alto2txt/) and maintained by @andrewphilipsmith through his account: [pypi.org/user/andysmith](https://pypi.org/user/andysmith/).
> 
> @davanstrien or others (@DavidBeavan perhaps?) if you would like this taken down we can try to sort (apologies in advance if so to @andrewphilipsmith). Also: is there a ticket for `Living-with-Machines` regarding future managing libraries generally?

I think if it's already up, it's probably not worth taking it down. 

> Also: is there a ticket for `Living-with-Machines` regarding future managing libraries generally?

I don't think so, but I think this would be good to discuss/document. In particular, how much we rely on people's motivations to maintain stuff that they worked on for career reasons vs institutions taking on maintenance responsibility. 

We may also want to consider adding some kind of 'maintenance' status header to our repositories to indicate if — and in what form — repositories are being maintained?

**Comment by griff-rees** [comment]
@davanstrien sure, can figure the `maintenance` status at some point, and having a central account to solve that might help. Finally just made ones for `PyPI` and `TestPyPI`, figure that's a starting point. See: #59.
